name: Deploy to Amazon ECS

on:
  push:
    branches-ignore:
      - master

permissions:
  contents: read

jobs:
  deploy:
    name: GitHub Actions
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
